# Generated by Django 5.0.4 on 2024-04-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knihovna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboniment', models.IntegerField()),
                ('nazev_knihy', models.CharField(max_length=150)),
                ('datum_vypujceni', models.DateTimeField(auto_now_add=True)),
                ('datum_vraceni', models.DateTimeField(blank=True, null=True)),
                ('prodlouzit', models.BooleanField(default=False)),
                ('novy_datum', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
